- name: Installs the AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Set up AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"

- name: Reboot the instance
  win_reboot:

- name: Print out the domain list 
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list

- debug:
   var: domain_list


