- name: install package
  win_chocolatey:
    name: "{{ package_name }}"
    package_params: "{{ parameters }}"
    state: present
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: start service
  win_service:
    name: "{{ service_name }}"
    state: started
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: config firewall
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    protocol: "{{ protocol_name }}"
    action: allow
    direction: in
    state: present
    enabled: yes

